- name: Join CentOS to Windows domain
  hosts: 51.145.230.155
  become: yes  

  vars_prompt:
    
    - name: "username"
      prompt: "Zadej Domenový username: "
   
    - name: "password"
      prompt: "Zadej Domenové heslo: "
   
    - name: "DomainName"
      prompt: "Nazev Domeny: "

    - name: "DomainController"
      prompt: "Domain Server: "

    - name: "computerOU"
      prompt: "computerOU: "

    - name: "LinuxDomainAdmin"
      prompt: "Linux Domain Admin: "

  tasks:
  - name: Join
    include_tasks: roles/tasks/main.yaml
