---
# Hide sensitive information from task output
adjoin_no_log: true

# Common settings for all domains
adjoin_sssd_homedir: '/home/%u'
adjoin_sssd_default_shell: '/bin/bash'
# Please note that disabling arcfour-hmac-md5 can NOT be done without some
# work on the AD controller's side
# Configure sudo permissions for the administrative groups in this file
adjoin_configure_sudo: false

