---
packages:
  - 'openldap-clients'
  - 'krb5-workstation'
  - 'sssd'
  - 'samba-winbind-clients'
  - 'oddjob-mkhomedir'
  - 'authconfig'
  - 'samba-common'
  - 'samba-common-tools'
  - 'realmd'
  - 'adcli'
modules:
  - 'pexpect'

openldap_conffile: '/etc/openldap/ldap.conf'

os_specific_services:
  - {'name':'oddjobd', 'enabled':'yes', 'masked':'no', 'state':'started'}
